pull_request_rules:
  - name: Automatic merge
    conditions:
      - "-draft"
      - "#approved-reviews-by>=1"
      - "#status-failure=0"
    actions:
      merge:
        strict: true
        strict_method: rebase
        method: squash
